### PR TITLE
Finished HW1

### PR DESCRIPTION
**Pull request by TimmyYoung**
Changes:
1. Completed HW1 solution after initializing repo/ssh.
________
Please review my attempt at the homework solution.
I would be happy to learn any new java-script tips or tricks if my code looks clunky (: .
Just looking for a second-pair of eyes and any sort of feedback. Thanks!

### CODE REVIEW

**Review by KSKRLIFE — COMMENTED** [review]
Hello Timmy,
FYI, I am a beginner to Javascript. your code looks awesome and here are few things I feel can be reviewed.

With ES6 Javascript it's suggested to use let or const in place of var.
This code is printing numbers till 99 and not including 100.(we can change counter < 100
to counter <=100)
Use of {} after if and else if statements.(just a thought though not necesary)

**Comment by rohan-singh1** [comment]
Hi Timmy. The code can be further optimized by checking for divisibility by both 5 and 3 inside one of the conditions to check for divisibility by one number, either 5 or 3. That will reduce the number of required comparisons.

**Comment by TimmyYoung** [comment]
I appreciate the feedback!! Thank you for catching that bug @KSKRLIFE. I did this after a 12 hour shift so I was sure their had to be at least on bug xD. 

Thanks for the tip for the optimization! @rohan-singh1

**Comment by SwaroopaSK** [comment]
Hi Timmy,
The code looks good, just that as Sai mentioned counter has to <= 100.

**Pull request merged**
